language: scala
sudo: required
jdk:
- oraclejdk8
env:
  global:
  - TRAVIS_NODE_VERSION="8"
  - secure: hN+neHa2Xg7kTjtxj+lnkBRtsBqZ7GuLsEKqQTM5OmxCN1hU5Vx1gmfDqTBS+B8oIKvm5fBpaByEcMQvuG/VhFCDz/UabCYABc4FYvy9CLlYIbKOmPrbtRHSZb7f4cAN5wtUwgVfuQtyZPIDk57o892ZXLoaExNC8KOd5u4eFctBw36wIC51ZZFWJazLtbyzcCLe0oHw2HOj2T7e/fis4febGiBu51hfbC+r13FShMgJDnUtTNhVmCzaAZLKnQ+T42fljKBlSFRiEsgZTe+TuyPzs8aZbPr5zs/27SCdvYWFtJ5jM1f42ePGr4Hs1yNah4IE1ppv76H35NpxPMfMZTshvpGz4wWJstua4b1PVCE8UnrVgpo42obBeb41KsQ8PZoUkVsN9LIH+7AvA4YHj8LP+5ItUlvFCsDIzJBdhk2Saz6XhI2NIXys3P0cjYE75D9gqEIypZHSy/3GTFS7A6QNryQXm6D1TsctKAkcscHA0bolwm/vAYmG1hLl2BX5lJQbdgfgtjwT0zHH+urNksMjDvd3U9XnEGTvqGSRVG05uw+2uWKZYy/01cPeRE/2DDKmXgwGBVNrtgGIBCFPxK88VqIGsUZeoVhnVyMFhOaIPrrLTd9wn/a+n1WrRajbz/8K1ee02VdEymOfNDYfu2LSRNbrFzg/ZzFit4zIqT8=
  - secure: OFUEbQhmD/pqMegCSQn/lEYS4FAbwnA9i+1791Og6LGztKbOqfNdplhaAow6F1Z2ONer0rf05gQtrgz5lx3OJJXB5FGzzUEmycmfSX/CIGSsSs1DhC+oP98W5kZzeyqd2Xx8+PCmw4Q0YQjd2TEkdLGDdMmvtQY+2GuPvpf4Sps48/X+W/hO9C2S3Xg+xU6LOiMlxu2E0aL28258C1ElPi6IUkGHgZ2IO57U8sqJawSfYjX5iPb0pwoTb94l+xrOtDhm5b265WRiJqXP1nWwHIxtnVvlDuIvjyCfS1BmqzyrC2X6RZzIzSOHS4WY3gtgWqNqCZzOoUY1LvMiP/4RXuPj4+zKBwgpoBqKaAwoyMM2yjYQRaTZAAH8zssPthuWiuQd302CQvJtxGqNiK68YdUNRRR7+uncMW9u8K8q3Sw+eR0XhvX6PyM0qXB5BIplF6W1im3bxwdmIzzPfg9Ggm8R3gBLrVJ/VIMczk6CRGs0LAiFU3UKDcmgWYdydos3b9/XS4XmRK4Qx53iJeUr1qN0/K547oq9+AAPT3/KAuchunIFTva9tM1RYETy7+IbqMdS3IjnatFolb30y57bLg0/BUGkFJnbLJmfSW5a25UaJWyhloqg60iL2islWrgdOFackcOLGXeMU43icZKPghK+iwkL+WGtjU5Nn7FXz8U=
  - secure: Q0fTuJWAb05Ks9YpUvOdq73qYbD50NbdOQLZTOx3DzdLkl6Gfij/s0BZE0tsB9dXWUI9rgiEaSyqyeuTVDWnVfLDaYd7kTEfbE3iyrdWGv/+RLxHonS1e5PsxE8OFNO8Jp3P4aniWTEgkDq4qLvI6Ytvo3AnEp384ncC+bcVUSJf7brGyguSKn9b+DBG9RyWDnov7z+xmhOKM7EpXki8hSi05Z+bNWq9vV2cbHKuGRQLM7ZidwA78MftQumP6bXWUpksQnKrfcoxI6XxyG8MEVKcHJ/JduAyhpsv0WnIk8yQtWFDf9ZRl82fSGR/tI4bTHoC+4HVgIgemqjyVe3A8uDcpVZxkanVtSxQWl9uckmI03huTTARmHCD9KXxCbGtLLwAHY4z3crlcZBuzCCYSDs6Z2Hx3ptHo6iDnRS34GBsN0SwY/a8s5aTnYMLSQQwACfkHedA+dYrdLGjSi0iyYiBQtz0ezg77qPev1UicUCXT6JBiSIJlPN+0tA2V7AR9QcY7G8iTcuPbB+ZDV4Di/5GWYZDotYnu9WKIFXrIcERvN9SqC/WMIB7ua/6o8LY6+BJ29LDD20XdEp9AS5Z5KBfNt/uNO6p0mSSYXI4vDSfv97QYFnHR8qttMfT/k5gULRvKkC/S15YMbUI3jITQz6CjIZ4PV0Sp1oHrBzYSm0=
before_install:
- nvm install 6
- nvm use 6
- node --version
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
- export PATH=$HOME/.yarn/bin:$PATH
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then openssl aes-256-cbc -K $encrypted_081278c3ec4a_key
  -iv $encrypted_081278c3ec4a_iv -in travis/secrets.tar.enc -out travis/secrets.tar
  -d; tar xv -C travis -f travis/secrets.tar; fi
script:
- sbt test
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ] && [ -n "$TRAVIS_TAG" ]; then sbt releaseEarly;
  fi
cache:
  yarn: true
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
